### ISSUE TITLE
Touch Support seems to be broken

### ISSUE THREAD

**Issue by marcohamersma** [clari/react-orderable#1]
First wanted to say that I've been looking for good orderable list components for the last few days and yours seems to be the only one only ones that's simple to understand and allows you to pass the items as `children` so thanks for making it.

I can't seem to get touch events to work correctly. I found that `getMousePosition(e)` expects `e.clientY` to be present, but it is not. I'm guessing this is because it's a touch event, but I'm not too familiar with how React handles this. 

In any case, it ends up setting `state.style.top` to NaN, which trows an error. What would be the best way to fix this?

**Comment by mking-clari** [comment]
@marcohamersma thanks for the feedback! I'm no longer maintaining this repo but I highly recommend taking a look at https://github.com/clauderic/react-sortable-hoc. we're migrating all of our code to this component, and many [developers I respect](https://github.com/bvaughn/react-virtualized/issues/377) are using it as well.
